Parameters:
  S3BucketName:
    Description: 'Building a S3 bucket with parameter'
    Type: 'String'

Resources:
  S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: 'PublicRead'
      BucketName: !Ref 'S3BucketName'

  EC21:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0915bcb5fa77e4892
      InstanceType: t2.nano

  RDS1:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '8'
      MasterUsername: db101
      MasterUserPassword: db101  
      DBInstanceClass: db.m1
      Engine: mysql



         