Parameters:
  MaxSizeASG:
    Description: "Enter the Max Size for the ASG"
    Type: String
  MinSizeASG:
    Description: "Enter the Min Size for the ASG"
    Type: String
  DesiredCapacityASG:
    Description: "Enter the desired capacity for the ASG"
    Type: String
  VPCZoneIdentifier:
    Description: "List the Subnet Ids of the instances"
    Type: List<AWS::EC2::Subnet::Id>
  KeyName:
    Description: "EC2 instance key name"
    Type: String
  InstanceType:
    Description: "EC2 instance type"
    Type: String

  ASGName:
    Description: "Enter unique ASG name"
    Type: String
  LCGName:
    Description: "Enter unique LCG name"
    Type: String

Mappings: 
  RegionMap: 
    us-east-1: 
      HVM64: "ami-0533f2ba8a1995cf9"
    us-east-1: 
      HVM64: "ami-0533f2ba8a1995cf9"

Resources:
    AutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AutoScalingGroupName: !Ref ASGName
        DesiredCapacity: !Ref DesiredCapacityASG
        LaunchConfigurationName: !Ref LaunchConfigfile 
        MaxSize: !Ref MaxSizeASG
        MinSize: !Ref MinSizeASG
        Tags:
          - Key: Name
            Value: Dutch Cfn ASG
            PropagateAtLaunch: 'true'
          - Key: Dept
            Value: French Cfn ASG
            PropagateAtLaunch: 'true'
        VPCZoneIdentifier: !Ref VPCZoneIdentifier
    LaunchConfigfile: 
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties: 
        KeyName: !Ref KeyName
        ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ]
        SecurityGroups: !Ref InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        LaunchConfigurationName: !Ref LCGName  
    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Existing Group
        SecurityGroupIds: !Ref sg-067b874e
          

 