Parameters:
  MaxSizeASG:
    Description: "Enter the Max Size for the ASG"
    Type: String
  MinSizeASG:
    Description: "Enter the Min Size for the ASG"
    Type: String
  DesiredCapacityASG:
    Description: "Enter the desired capacity for the ASG"
    Type: String
  VPCZoneIdentifier:
    Description: "List the Subnet Ids of the instances"
    Type: List<AWS::EC2::Subnet::Id>
  VPC:
    Description: "Enter VPC ID"
    Type: String
  PublicSubnet1:
    Type: String
    Description: The subnet where to launch the service
    Default: subnet-ID
  PublicSubnet2:
    Type: String
    Description: the subnet where to Launch the service
    Default: subnet-ID   
  KeyName:
    Description: "EC2 instance key name"
    Type: String
  InstanceType:
    Description: "EC2 instance type"
    Type: String
  ASGName:
    Description: "Enter unique ASG name"
    Type: String
  LCGName:
    Description: "Enter unique LCG name"
    Type: String 
  EC2SecurityGroupName:
    Description: "Enter security group name"
    Type: String 
  ALBSecurityGroupName:
    Description: "ID of existing ALB security group"
    Type: String  

Mappings: 
  RegionMap: 
    us-east-1: 
      HVM64: ami-0533f2ba8a1995cf9

Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref ASGName
        DesiredCapacity: !Ref DesiredCapacityASG
        LaunchConfigurationName: !Ref LaunchConfigfile 
        MaxSize: !Ref MaxSizeASG
        MinSize: !Ref MinSizeASG
        Tags:
          - Key: Name
           Value: Bihar Cfn ASG
           PropagateAtLaunch: 'true'
          - Key: Dept
           Value: Assam Cfn ASG
           PropagateAtLaunch: 'true'
        VPCZoneIdentifier: !Ref VPCZoneIdentifier  

  LaunchConfigfile: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      KeyName: !Ref KeyName
        ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ]
        SecurityGroups: 
          - !Ref InstanceSecurityGroup
        InstanceType: !Ref InstanceType
        LaunchConfigurationName: !Ref LCGName  

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic
        GroupName: !Ref EC2SecurityGroupName  
        VpcId: !Ref VPC      
        SecurityGroupIngress:
          - IpProtocol: tcp
           FromPort: 80
           ToPort: 80
           CidrIp: 0.0.0.0/0 
          - IpProtocol: tcp
           FromPort: 443
           ToPort: 443
           CidrIp: 0.0.0.0/0   
        SecurityGroupEgress:
          - IpProtocol: tcp
           FromPort: 80
           ToPort: 80
           CidrIp: 0.0.0.0/0  

  StateTargetGroup: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      Port: 80
      Protocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      TargetType: instance
      Matcher:
        HttpCode: "200"
      HealthyThresholdCount: 5
      VpcId: !Ref VPC
      HealthCheckEnabled: "true"
      

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: State-ALB
        Scheme: internet-facing
        Type: application
        Subnets: 
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2         
      SecurityGroupIds: sg-01f4c7f23d300704c   
      IpAddressType: ipv4
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions: 
      -  Order: 1
      RedirectConfig:
        Protocol: HTTPS
        Port: 443
        Host: #{host}
        Path: /#{path}
        Query: #{query}
        StatusCode: HTTP_301
  HTTPSListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        LoadBalancerArn: !Ref ApplicationLoadBalancer
        Port: 443
        Protocol: HTTPS
        Certificates: 
        -  CertificateARN: arn:aws:acm:ap-south-1:640393631002:certificate/d9c2e954-d4f8-406a-bbd3-e265fbe2c197
        DefaultActions:
        -  Order: 1
        TargetGroupArn: !Ref StateTargetGroup